MIN_COOK_TIME = 1
MAX_LENGTH_NAME = 128
MIN_VALUE_AMOUNT = 1
MAX_LENGTH_RECIPE_SHORT_LINK = 10

# PDF constants
PDF_TITLE = "Список покупок"
PDF_FILENAME = "shopping_list.pdf"
PDF_CACHE_TIME = 300  # 5 minutes
PDF_COLUMN_WIDTHS = [3, 1.5, 1.5]  # in inches
PDF_HEADER_FONT_SIZE = 14
PDF_BODY_FONT_SIZE = 12
PDF_TITLE_FONT_SIZE = 24
