# Generated by Django 4.2.21 on 2025-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Имя пользователя", max_length=150, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Фамилия пользователя", max_length=150, verbose_name="Фамилия"
            ),
        ),
    ]
